### ISSUE TITLE
Renaming Package to meet Guidelines

### ISSUE THREAD

**Issue by aelligp** [JuliaGeodynamics/JustPIC.jl#13]
The JuliaRegistrator Guidelines state that no Package should begin with 'Ju'. We've ran into this problem with JustRelax.jl. 
As you probably want to register JustPIC in the future, I suggest to rename it to your liking.

**Comment by luraess** [comment]
I hope we can make the case to still be able to register "Ju" starting package names.

**Comment by albert-de-montserrat** [comment]
~~JustRelax.jl~~ PleaseConverge.jl
~~JustPIC.jl~~ PleaseAdvect.jl/PleaseMove.jl
and can complement it with ~~FastIce.jl~~ PleaseChill.jl  :sunglasses:

**Comment by boriskaus** [comment]
Hmm, this suggests it may not converge. Do we want to live with that for the coming years?
What about PseudoTransient… ?

On 18. Oct 2023, at 10:00, albert-de-montserrat ***@***.***> wrote:

﻿

JustRelax.jl PleaseConverge.jl
JustPIC.jl PleaseAdvect.jl/PleaseMove.jl
and can complement it with FastIce.jl PleaseChill.jl 😎

**Comment by luraess** [comment]
Indeed, not ideal. We'll think about some good naming. But ideally we could make the case for `Ju**` naming...

**Comment by boriskaus** [comment]
The online registry says that this may simply not be merged automatically. Yet it also complains about lacking `[compat]` for the various packages.
I believe that was fixed meanwhile; yet you have to manually retrigger the registry for this to reconsider it again.
Let’s try and see if they are happy to merge this after all
